### ISSUE TITLE
running `crc delete` when an existing VM with the old drivers are present results in a panic on macOS

### ISSUE THREAD

**Issue by anjannath** [cfergeau/macadam#23]
The full stack trace when this happens:

```
[anath@anath-mac] github.com/crc-org/crc (teuf-macadam) % crc delete -f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xd8 pc=0x1059a0570]

goroutine 1 [running]:
github.com/cfergeau/macadam/pkg/machinedriver.(*Driver).Remove(0x140008e2460)
        /Users/anath/work/github.com/crc-org/crc/vendor/github.com/cfergeau/macadam/pkg/machinedriver/driver.go:456 +0x20
github.com/crc-org/crc/v2/pkg/crc/machine.(*virtualMachine).Remove(0x14000a9a180)
        /Users/anath/work/github.com/crc-org/crc/pkg/crc/machine/virtualmachine.go:72 +0x34
github.com/crc-org/crc/v2/pkg/crc/machine.(*client).Delete(0x140004112c0)
        /Users/anath/work/github.com/crc-org/crc/pkg/crc/machine/delete.go:19 +0xd4
github.com/crc-org/crc/v2/pkg/crc/machine.(*Synchronized).Delete(0x14000411300)
        /Users/anath/work/github.com/crc-org/crc/pkg/crc/machine/sync.go:70 +0x50
github.com/crc-org/crc/v2/cmd/crc/cmd.deleteMachine({0x106575aa0, 0x14000411300}, 0x22?, {0x1400013a318?, 0x104142a00?}, 0x1, 0x1)
        /Users/anath/work/github.com/crc-org/crc/cmd/crc/cmd/delete.go:65 +0x1cc
github.com/crc-org/crc/v2/cmd/crc/cmd.runDelete({0x10653bc08, 0x14000126020}, {0x106575aa0?, 0x14000411300?}, 0xb4?, {0x1400013a318?, 0x2f41cb280089fc18?}, 0x7e?, 0x25?, {0x0, ...})
        /Users/anath/work/github.com/crc-org/crc/cmd/crc/cmd/delete.go:71 +0x54
github.com/crc-org/crc/v2/cmd/crc/cmd.init.func3(0x105b0b52b?, {0xa?, 0x1400089fc18?, 0x0?})
        /Users/anath/work/github.com/crc-org/crc/cmd/crc/cmd/delete.go:34 +0x94
github.com/crc-org/crc/v2/cmd/crc/cmd.attachMiddleware.executeWithLogging.func1(0x1077fa380, {0x14000428ae0, 0x0, 0x1})
        /Users/anath/work/github.com/crc-org/crc/cmd/crc/cmd/root.go:170 +0xb0
github.com/spf13/cobra.(*Command).execute(0x1077fa380, {0x14000428ab0, 0x1, 0x1})
        /Users/anath/work/github.com/crc-org/crc/vendor/github.com/spf13/cobra/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1077fb1e0)
        /Users/anath/work/github.com/crc-org/crc/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/anath/work/github.com/crc-org/crc/vendor/github.com/spf13/cobra/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/anath/work/github.com/crc-org/crc/vendor/github.com/spf13/cobra/command.go:1034
github.com/crc-org/crc/v2/cmd/crc/cmd.Execute()
        /Users/anath/work/github.com/crc-org/crc/cmd/crc/cmd/root.go:106 +0xcc
main.main()
        /Users/anath/work/github.com/crc-org/crc/cmd/crc/main.go:8 +0x1c
```

**Comment by cfergeau** [comment]
The switch to macadam is a good opportunity to switch to crc 3.0, and we'll require running `crc delete` after upgrading, so this usecase has to do something useful, not crash :)
We can also add a preflight check detecting older VM instances and instructing the user to run `crc delete`
