### ISSUE TITLE
Panic when starting macadam with microshift vfkit 

### ISSUE THREAD

**Issue by lstocchi** [cfergeau/macadam#26]
followed steps from https://github.com/cfergeau/crc/blob/macadam/docs/macadam-testing.md by downloading the microshift vfkit bundle.
The first time looked like it was succeeded "INFO CRC instance is running with IP 127.0.0.1", then it failed at connecting with SSH
"Failed to connect to the CRC VM with SSH -- virtual machine might be unreachable: Temporary error: ssh command".
After deleting and setup the instance again, I'm facing this error

```
luca@MacBook-Pro-di-Luca crc % ./out/macos-arm64/crc start --bundle ~/Downloads/crc_microshift_vfkit_4.17.8_amd64_990.crcbundle
/usr/bin/security -i
/usr/bin/security delete-generic-password -s crc-test -a foo
WARN Using crc_microshift_vfkit_4.17.8_amd64_990.crcbundle bundle, but crc_microshift_vfkit_4.17.7_arm64.crcbundle is expected for this release 
INFO Using bundle path /Users/luca/Downloads/crc_microshift_vfkit_4.17.8_amd64_990.crcbundle 
INFO Checking if running macOS version >= 13.x    
sw_vers -productVersion
INFO Checking if running as non-root              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking if running on a supported CPU architecture 
INFO Checking if crc executable symlink exists    
INFO Checking minimum RAM requirements            
INFO Check if Podman binary exists in: /Users/luca/.crc/bin/oc 
INFO Checking if running emulated on Apple silicon 
INFO Checking if vfkit is installed               
INFO Checking if old launchd config for tray and/or daemon exists 
INFO Checking if crc daemon plist file is present and loaded 
bash -c launchctl list | grep com.redhat.crc.daemon | awk '{print $1}'
INFO Checking SSH port availability               
INFO Loading bundle: crc_microshift_vfkit_4.17.8_amd64_990... 
/usr/bin/security find-generic-password -s crc -wa compressed-pull-secret
INFO Creating CRC VM for MicroShift 4.17.8...     
INFO Generating new SSH key pair...               
INFO Starting CRC VM for microshift 4.17.8...     
/Users/luca/Public/Work/github.com/crc/crc/out/macos-arm64/vfkit --cpus 2 --memory 4096 --bootloader efi,variable-store=/Users/luca/.crc/machines/crc/efistore.nvram,create --device virtio-serial,logFilePath=/Users/luca/.crc/machines/crc/vfkit.log --device virtio-fs,sharedDir=/Users/luca,mountTag=dir0 --device virtio-rng --device virtio-blk,path=/Users/luca/.crc/machines/crc/crc.img --device virtio-vsock,port=1024,socketURL=/Users/luca/.crc/tap.sock,listen --timesync vsockPort=1234
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103dbd2a0]

goroutine 1 [running]:
github.com/crc-org/crc/v2/pkg/drivers/vfkit.(*Driver).Start(0x140006c5ec0)
	/Users/luca/Public/Work/github.com/crc/crc/pkg/drivers/vfkit/driver_darwin.go:282 +0x7c0
github.com/crc-org/crc/v2/pkg/crc/machine.startHost({0x104b38c48, 0x140009c2820}, 0x14000456080)
	/Users/luca/Public/Work/github.com/crc/crc/pkg/crc/machine/start.go:702 +0x40
github.com/crc-org/crc/v2/pkg/crc/machine.(*client).Start(0x140006c55c0, {0x104b38c48, 0x140009c2820}, {{0x16d4f788d, 0x45}, 0x1000, 0x2, 0x1f, {0x0, 0x0}, ...})
	/Users/luca/Public/Work/github.com/crc/crc/pkg/crc/machine/start.go:384 +0xde0
github.com/crc-org/crc/v2/pkg/crc/machine.(*Synchronized).Start(0x140006c5600, {0x104b38c10?, 0x140009e3560?}, {{0x16d4f788d, 0x45}, 0x1000, 0x2, 0x1f, {0x0, 0x0}, ...})
	/Users/luca/Public/Work/github.com/crc/crc/pkg/crc/machine/sync.go:93 +0xa8
github.com/crc-org/crc/v2/cmd/crc/cmd.runStart({0x104b38c10, 0x140009e3560})
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/cmd/start.go:117 +0x4b8
github.com/crc-org/crc/v2/cmd/crc/cmd.init.func11(0x105ca6c20, {0x9?, 0x14000135c18?, 0x0?})
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/cmd/start.go:57 +0x58
github.com/crc-org/crc/v2/cmd/crc/cmd.attachMiddleware.executeWithLogging.func1(0x105ca6c20, {0x140004ad060, 0x0, 0x2})
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/cmd/root.go:170 +0xb0
github.com/spf13/cobra.(*Command).execute(0x105ca6c20, {0x140004ad040, 0x2, 0x2})
	/Users/luca/Public/Work/github.com/crc/crc/vendor/github.com/spf13/cobra/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x105ca6660)
	/Users/luca/Public/Work/github.com/crc/crc/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/luca/Public/Work/github.com/crc/crc/vendor/github.com/spf13/cobra/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/luca/Public/Work/github.com/crc/crc/vendor/github.com/spf13/cobra/command.go:1034
github.com/crc-org/crc/v2/cmd/crc/cmd.Execute()
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/cmd/root.go:106 +0xcc
main.main()
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/main.go:8 +0x1c
```

**Comment by lstocchi** [comment]
closing as I tried again from scratch today and it does not happen. I'll reopen if I see it again but it could be something related to my machine
